- setup.py
`BinLogStreamReader` class in `pymysqlreplication` misreads `datetime(3)` columns. e.g
the value `2019-12-05 15:05:18.517` is converted into python's `datetime.datetime(2019, 12, 5, 15, 5, 18, 517)`, then when we want to get the isoformat of this datetime object, we get `2019-12-05T15:05:18.000517` .
This happens during binlog replication only. I tried the latest version of `pymysqlreplication` and the bug was gone.
> v1.0.7: bump mysql-replication to latest version

- .circleci/config.yml
- .noserc
- .pylintrc
- docker-compose.yml
- setup.py
- tap_mysql/__init__.py
- tap_mysql/connection.py
- tap_mysql/sync_strategies/binlog.py
- tap_mysql/sync_strategies/common.py
- tap_mysql/sync_strategies/full_table.py
- tap_mysql/sync_strategies/incremental.py
- tests/test_full_table_interruption.py
- tests/test_tap_mysql.py
- tests/utils.py
Binary columns will now be supported with this PR.
The values need to be encoded so that json.dumps of records works. I choose hexadecimal encoding because in Snowflake, the function `To_BINARY` encodes data using `hex` by default and it's convenient.
To communicate that a column is binary in Json schema, I used `{"type": ["null", "string"], "format": "binary"}` so that targets can create a binary column instead of string .
This change is part #1 to achieve this https://transferwise.atlassian.net/browse/AP-111
PS: tests and circleci are unusable as they are now, they need to be refactored. Will do that in a separate PR.
> v1.1.0: support binary/varbinary columns

- setup.py
- tap_mysql/sync_strategies/binlog.py
@ivan-transferwise made same great work and measured the current performance of tap-mysql and [target-snowflake](https://github.com/transferwise/pipelinewise-target-snowflake) and realised that tap-mysql currently sends data slower than target-snowflake can process it. That means if we want to reduce replication lag from mysql to snowflake we need to improve this tap first.
After some further cProfile-ing using a database where this tap currently processes ~1600 events/seconds from the binlog, we found that the most of the time spent on [update_bookmark](https://github.com/transferwise/pipelinewise-tap-mysql/blob/07fa7d7b6e67f7b256f8c9c241b9571993d6d55c/tap_mysql/sync_strategies/binlog.py#L223) and [singer.write_boookmark](https://github.com/transferwise/pipelinewise-tap-mysql/blob/07fa7d7 …
> [AP-483] Update bookmark only before writing state message

- setup.py
- tap_mysql/sync_strategies/binlog.py
This PR is to update bookmark one more time right after when every event processed from the binlog. This is required to send binlog positions at the very end of the process that is out of the `UPDATE_BOOKMARK_PERIOD`.
> [AP-483] Update bookmark when reading bookmark finished

- setup.py
- tap_mysql/sync_strategies/binlog.py
This PR is to update bookmark only if the `log_file` and `log_pos` is not Null.
> [AP-483] Update bookmark only if binlog position is valid

- tap_mysql/__init__.py
- tap_mysql/sync_strategies/binlog.py
- tests/test_tap_mysql.py
Based on upstream code: https://github.com/singer-io/tap-mysql/pull/111 and https://github.com/singer-io/tap-mysql/pull/120
I changed the "string" to "object" type (as peter mentioned in slack) instead, so it is recognized in the targets as jsonb automatically. The fastsync seems to work without any changes (mysql -> postgres in my case)
> Json support

- tap_mysql/connection.py
- tests/test_tap_mysql.py
- tests/utils.py
This PR is getting an optional session_sqls parameter from the connection config and running each of them automatically right after the mysql/mariadb connection has made.
Using this approach we don't hardcode session parameters, every tap can have different values and we support different different session parameter names used by the different version of mariadb/mysql.
Example `config.json`:
```
{
"host": "localhost",
"port": "3306",
"user": "root",
"password": "password",
"session_sqls": [
"SET @@session.wait_timeout=14400",
"SET @@session.net_read_timeout=7200"
]
}
```
If `session_sqls` not specified in `config.json` then it defaults to:
```
['SET @@session.time_zone="+0:00"',
'SET @@session.wait_timeout=28800',
'SET @@session.net_read_timeout=3600',
'SET …
```
> [AP-372] Add optional session_sqls connection parameter

- CHANGELOG.md
- setup.py
New release candidate to PyPI: 1.3.1
Changelog:
1.3.1 (2020-06-15)
-------------------
-  Fix dependency issue by removing `attrs` from `setup.py`
-  Bump `pymysql` to `0.9.3`
> v1.3.1 and changelog

- setup.py
PyMSQL `0.9.3` has some not backward compatible changes in handling invalid datetime columns. Some changes introduced in `0.8.1` that breaks the current expected behaviour of the driver.
The expected old behaviour is detailed and used in this PR: https://github.com/transferwise/pipelinewise/pull/444
If 2 rows were inserted where date_col is `2017-02-31 00:00:00` and  `2000-00-00 17:18:40` then running `select concat(date_col, ''), date_col from table` should return:
```
concat(date_col, '') |   date_col
------------------------------------------------------------
2017-02-31 00:00:00  |  2017-03-03 00:00:00
2000-00-00 17:18:40  |  1999-11-30 17:18:40 
```
This behaviour changed in pymysql `0.8.1`, but the current implementation requires it. This PR revers pymysql to the old pymsql.
We can …
> Revert to pymysql 0.7.11

- CHANGELOG.md
- setup.py
New release candidate to PyPI: 1.3.2
Changelog:
1.3.2 (2020-06-15)
-------------------
-  Revert `pymysql` back to `0.7.11`.
`pymysql >= 0.8.1` introducing some not expected and not backward compatible changes how it's dealing with invalid datetime columns.
> v1.3.2 and changelog

- tap_mysql/__init__.py
- tap_mysql/discover_utils.py
- tap_mysql/stream_utils.py
- tap_mysql/sync_strategies/binlog.py
- tap_mysql/sync_strategies/common.py
- tests/test_tap_mysql.py
- tests/utils.py
When columns get added/renamed in the source tables, tap-mysql, during binlog replication, starts sending the new data in the RECORD messages but doesn't send new SCHEMA message before that. This results in the target connector ignoring the data in these columns because the target table is not up to date , and we lose data in the newly added/renamed columns.
Detect new columns, incl renamed one, by comparing the columns in the binlog event to the stream schema, and if they are any additional columns, run discovery and send a new SCHEMA message to target.
* moved some function to their dedicated `*_utils.py` file for reusability and modularisation.
* Added test to make sure the changes work.
> [AP-742] Detect new/renamed columns from binlog message and update schema

- tap_mysql/sync_strategies/binlog.py
- tests/test_tap_mysql.py
The tap fails sometimes with error 
```
TypeError: argument of type 'NoneType' is not iterable
```
in the function `tap_mysql/sync_strategies/binlog.py:row_to_singer_record`
The cause of this error is after a new change is detected in schema during LOG_BASED, the desired columns are not updated properly thus the rows are not filtered properly to ignore unsupported type columns, in this case a `blob`.
As part of the updating schema, update the columns list to contains only supported type columns.
After deleting  a column, old binlog events will refer to this column with `__dropped_col_{SOME_INT}__`, we don't care about these cases when detecting new changes, so we filter out these columns with the regex pattern `r'__dropped_col_\d+__'`.
> [AP-742] Fix error after new discovery 

- tap_mysql/sync_strategies/binlog.py
- tests/test_tap_mysql.py
New schema after discovery contains properties of unsupported types. These properties don't have `type` which makes the targets fail because they expect every property to have a `type` property.
The error caused in target is:
```
if list(v.values())[0][0]['type'] == 'string':
TypeError: string indices must be integers
```
Example of published schema message after a new column of type `blob` which is unsupported has been added:
```
SchemaMessage(type=SCHEMA, stream=tap_mysql_test-binlog_1, schema={'properties': {'id': {'inclusion': 'available', 'minimum': -2147483648, 'maximum': 2147483647, 'type': ['null', 'integer']}, 'date_updated': {'inclusion': 'available', 'format': 'date-time', 'type': ['null', 'string']}, 'data': {'inclusion': 'unsupported', 'description': 'Unsupported column type …
```
> [AP-742] Drop unsupported properties from new schema before flushing

- tap_mysql/discover_utils.py
- tap_mysql/sync_strategies/binlog.py
- tap_mysql/sync_strategies/common.py
- tests/test_tap_mysql.py
Currently, when creating the stream's schema to be sent to targets, the `time` sql type is sent as a datetime format, it should be instead sent as time format to make the target table as identical as possible to the source once.
Process time differently by setting format to `time` and properly format it the values when creating a singer record.
> [AP-774] Handle time data type separately

- .gitignore
- setup.py
- tap_mysql/discover_utils.py
- tap_mysql/sync_strategies/binlog.py
- tap_mysql/sync_strategies/common.py
- tests/test_tap_mysql.py
`pipelinewise-tap-mysql` currently doesn't support MySQL [spatial data types](https://dev.mysql.com/doc/refman/5.7/en/spatial-type-overview.html)
This change adds support for spatial data types by converting them to geojson by using MySQLs `ST_AsGeoJSON` function for `FULL_TABLE` and `INCREMENTAL` syncs and `plpygis` to convert `wbk` to geojson for `LOG_BASED` syncs.
https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1401189673/Change+Classifications+and+Expectations) Label (`change:standard`, `change:impactful`, `change:emergency`)
> [NO-REF] Support MySQL spatial types

- setup.py
- tap_mysql/__init__.py
Dependabot is about to upgrade pylint 2.4 to 2.6.0 in [this PR](https://github.com/transferwise/pipelinewise-tap-mysql/pull/47) but the new pylint gives error:
```
tap_mysql/__init__.py:294: [W0613(unused-argument), sync_non_binlog_streams] Unused argument 'config'
```
Bump pylint and fix pylint error
> Bump pylint from 2.4 to 2.6.0

- tap_mysql/__init__.py
- tap_mysql/discover_utils.py
- tap_mysql/sync_strategies/binlog.py
- tap_mysql/sync_strategies/common.py
- tests/test_tap_mysql.py
In LOG_BASED replication, changes to a table structure are detected by analysing columns in binlog events.
When a unsupported column is in the stream, that causes the discovery to run over and over again, adding unnecessary overhead to the sync.  
* add datatype to properties breadcrumbs
* Aggregate all supported columns in a global variable.
* Added a new function `is_supported_column_type` that analyses the column datatype and checks if it's supported.
* Only run discovery mid-sync if detected columns are of supported types or new columns that we don't know anything about.
* Keep a set of ignored columns at runtime to not have to check whether we need to ignore a column or not every single time. 
PS: Every binlog event has list of columns, with their name and types ..etc, the column …
> [AP-859] Stop constant discovery when running into known unsupported column types 

- tap_mysql/connection.py
When setting session SQL such as connection timeouts, it's possible
to get an error like
```
(1229, "Variable 'connect_timeout' is a GLOBAL variable and should be
set. with SET GLOBAL")
```
The previous error handling just swallowed MySQL error messages,
making it difficult or impossible to debug errors with connection
settings.
Add a simple change to log the DB error message, so that errors
can be diagnosed more easily.
> Log error message for session SQLs

- Makefile
- README.md
- tap_mysql/sync_strategies/binlog.py
- tests/integration/test_tap_mysql.py
- tests/unit/sync_strategies/test_binlog.py
With the tap now having GTID support, switching to using GTID for bookmark requires a one-off task of finding the equivalent gtid and updating the state file, this can mean a lot of work if have numerous pipelines.
For MariaDB, when `use_gtid` flag is true and there is no gtid but there a binlog file and position in the state, then use that to lookup the equivalent gtid thanks to the sql function `BINLOG_GTID_POS`.
For Mysql, there is no such option, the closest is to use mysqlbinlog library which mean it would become a system requirement of this tap, we decided to just fail instead, so the user has to find the gtid position and manually update the state.
> AP-1139 dynamically infer gtid from binlog coordinates for MariaDB 

- .github/workflows/ci.yaml
- Makefile
- tap_mysql/sync_strategies/binlog.py
- tests/unit/sync_strategies/test_binlog.py
When using mariadb DB and enabling GTID for a tap that has been using binlog coordinates, the code will try to lookup the equivalent GTID using the sql function `BINLOG_GTID_POS`, this function can return comma separated gtids which was not expected.
Process the results `BINLOG_GTID_POS` and find the right gtid by comparing the second element to host's server ID.
> AP-1183: handle case when BINLOG_GTID_POS returns many comma separated gtids

- .github/CODEOWNERS
- setup.py
- tap_mysql/connection.py
- tap_mysql/sync_strategies/binlog.py
Currently, tap-mysql will only connect without SSL, unless certificates are specified. Going forward, source servers really need to be protected a little better if possible.
Attempt SSL connection without certificate before falling back to regular connections
> Prefer SSL connection to source

- .github/workflows/pythonpublish.yml
Current uploader is not uploading
Update PyPi uploader to automate new versions
> Update PyPi uploader to automate new versions
